"""A reference Milvus gRPC tokenizer backed by MeCab (mecab-ko).

This is the "attach a real libmecab as a custom CJK tokenizer" path: MeCab runs in
this process, Milvus calls it over gRPC per document / per query. It is the direct
analogue of the in-process ``textsearch_ko`` PostgreSQL C extension, but the
language boundary (C libmecab vs. Rust/C++ tantivy) is crossed by RPC instead of by
linking, which is exactly why it needs no Milvus rebuild.

Wire it into a collection with an analyzer config like:

    {"tokenizer": {"type": "grpc", "endpoint": "http://mecab-tokenizer:50051"}}

Run:

    ./generate_stubs.sh          # once, produces tokenizer_pb2*.py
    python server.py --port 50051 --mecab-args "-d /usr/lib/mecab/dic/mecab-ko-dic"

The offset / POS-filter logic lives in ``mecab_analyze`` and is unit-tested there;
this file is just the MeCab binding plus the gRPC plumbing.
"""

from __future__ import annotations

import argparse
import logging
from concurrent import futures
from typing import List

import grpc

from mecab_analyze import DEFAULT_STOP_POS, Morph, tokenize

# Generated by ./generate_stubs.sh from tokenizer.proto
import tokenizer_pb2
import tokenizer_pb2_grpc

logger = logging.getLogger("mecab_tokenizer")


class MeCabTagger:
    """Thin wrapper over libmecab via the ``mecab-python3`` binding.

    ``mecab_args`` is passed straight to ``MeCab.Tagger`` -- use it to point at a
    specific dictionary, e.g. ``"-d /usr/lib/mecab/dic/mecab-ko-dic"``.
    """

    def __init__(self, mecab_args: str = ""):
        import MeCab  # imported lazily so the module stays importable without MeCab

        self._tagger = MeCab.Tagger(mecab_args)

    def analyze(self, text: str) -> List[Morph]:
        morphs: List[Morph] = []
        node = self._tagger.parseToNode(text)
        while node:
            surface = node.surface
            if surface:  # BOS/EOS nodes have empty surface -> skipped
                # mecab-ko-dic feature CSV: first field is the POS tag.
                pos = node.feature.split(",")[0]
                morphs.append(Morph(surface, pos))
            node = node.next
        return morphs


def _resolve_options(request, default_stop_pos, default_lowercase):
    """Apply per-request parameter overrides (keep_pos / stop_pos / lowercase)."""
    stop_pos = default_stop_pos
    lowercase = default_lowercase
    keep_pos = None
    for p in request.parameters:
        if p.key == "stop_pos":
            stop_pos = frozenset(p.values)
        elif p.key == "keep_pos":
            keep_pos = frozenset(p.values)
        elif p.key == "lowercase" and p.values:
            lowercase = p.values[0].strip().lower() in ("1", "true", "yes")
    return stop_pos, keep_pos, lowercase


class TokenizerServicer(tokenizer_pb2_grpc.TokenizerServicer):
    def __init__(self, tagger, stop_pos=DEFAULT_STOP_POS, lowercase=True):
        self._tagger = tagger
        self._stop_pos = stop_pos
        self._lowercase = lowercase

    def Tokenize(self, request, context):
        stop_pos, keep_pos, lowercase = _resolve_options(
            request, self._stop_pos, self._lowercase
        )
        try:
            morphs = self._tagger.analyze(request.text)
        except Exception as exc:  # never take the whole index build down on one doc
            logger.exception("mecab analyze failed: %s", exc)
            context.set_code(grpc.StatusCode.INTERNAL)
            context.set_details(f"mecab analyze failed: {exc}")
            return tokenizer_pb2.TokenizationResponse(tokens=[])

        # keep_pos is a whitelist expressed as "drop everything not in it"
        effective_stop = stop_pos
        if keep_pos is not None:
            all_pos = {m.pos for m in morphs}
            effective_stop = frozenset(all_pos - keep_pos)

        toks = tokenize(request.text, morphs, stop_pos=effective_stop, lowercase=lowercase)
        return tokenizer_pb2.TokenizationResponse(
            tokens=[
                tokenizer_pb2.Token(
                    text=t.text,
                    offset_from=t.offset_from,
                    offset_to=t.offset_to,
                    position=t.position,
                    position_length=t.position_length,
                )
                for t in toks
            ]
        )


def serve(port: int, mecab_args: str, workers: int, lowercase: bool):
    tagger = MeCabTagger(mecab_args)
    server = grpc.server(futures.ThreadPoolExecutor(max_workers=workers))
    tokenizer_pb2_grpc.add_TokenizerServicer_to_server(
        TokenizerServicer(tagger, lowercase=lowercase), server
    )
    server.add_insecure_port(f"[::]:{port}")
    server.start()
    logger.info("mecab gRPC tokenizer listening on :%d", port)
    server.wait_for_termination()


def main():
    ap = argparse.ArgumentParser(description="Milvus MeCab gRPC tokenizer")
    ap.add_argument("--port", type=int, default=50051)
    ap.add_argument(
        "--mecab-args",
        default="",
        help='args passed to MeCab.Tagger, e.g. "-d /usr/lib/mecab/dic/mecab-ko-dic"',
    )
    ap.add_argument("--workers", type=int, default=16)
    ap.add_argument(
        "--no-lowercase",
        action="store_true",
        help="do not lowercase Latin tokens (default: lowercase, matching Milvus built-ins)",
    )
    args = ap.parse_args()
    logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")
    serve(args.port, args.mecab_args, args.workers, lowercase=not args.no_lowercase)


if __name__ == "__main__":
    main()
